version: "2"
services:
    www:
        build: .
        container_name: app
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        
        depends_on: 
            - db

        links:
            - db

        networks:
            - default
    db:
        image: mariadb:latest
        container_name: db
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - "4306:3306"

        expose:
            - 3306
        environment:
            MYSQL_DATABASE: web_project
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8090:80
        environment:
            PMA_HOST: db
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test

volumes:
  db_data:
